import type {Metadata} from "next";
import {Assistant, Gideon_Roman, Staatliches} from "next/font/google";
import "./globals.css";
import {NavigationBar} from "@/components/NavigationBar";
import {Footer} from "@/components/Footer";


const primary = Staatliches({
    weight: "400",
    variable: "--font-primary",
});

const secondary = Gideon_Roman({
    weight: "400",
    variable: "--font-secondary",
})

const mainFont = Assistant({
    weight: "400",
    variable: "--font-main",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${primary.variable} ${secondary.variable} antialiased ${mainFont.variable}`}
        >
        <NavigationBar/>
        <div className={"mt-[-56px]"}>
            {children}
        </div>
        <Footer/>
        </body>
        </html>
    );
}
