import type {Metadata} from "next";
import {
    Castoro_Titling,
    Geist,
    Geist_Mono,
    Open_Sans,
    Playfair,
    PT_Sans, Public_Sans,
    Rubik_Glitch,
    Staatliches
} from "next/font/google";
import "./globals.css";
import {NavigationBar} from "@/components/NavigationBar";


const primary = Staatliches({
    weight: "400",
    variable: "--font-primary",
});

const secondary = PT_Sans({
    weight: "400",
    variable: "--font-secondary",
})

const mainFont = Public_Sans({
    weight: "400",
    variable: "--font-main",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${primary.variable} ${secondary.variable} antialiased ${mainFont.variable}`}
        >
        <NavigationBar/>
        <div className={"mt-[-56px]"}>
            {children}
        </div>
        </body>
        </html>
    );
}
